[env:lolin32]
platform = espressif32
board = lolin32
framework = arduino
monitor_speed = 115200
lib_archive = false
lib_deps =
    madhephaestus/ESP32Servo@^3.0.5
    gilmaimon/ArduinoWebsockets@^0.5.4
